//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataModel.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
	using GW2NET.Items.ApiModels;
	using GW2NET.Skins;

    /// <summary>Convertes a <see cref="SkinDataModel"/> into a <see cref="ArmorSkin"/> object.</summary>
    public sealed partial class ArmorSkinConverter : IConverter<SkinDataModel, ArmorSkin>
	{
	    private readonly ITypeConverterFactory<SkinDataModel, ArmorSkin> converterFactory;

		/// <summary>Initalizes a new instance of the <see cref="ArmorSkinConverter"/> class.</summary>
        /// <param name="converterFactory">The <see cref="ITypeConverterFactory{TSource,TTarget}"/>.</param>
		private ArmorSkinConverter(ITypeConverterFactory<SkinDataModel, ArmorSkin> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException(nameof(converterFactory));
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException(nameof(value));
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'ArmorSkin' (if any)
    	partial void Merge(ArmorSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class ArmorSkinConverter
		{
		    partial void Merge(ArmorSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region BootsSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="BootsSkin"/>.</summary>
    public sealed partial class BootsSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new BootsSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'BootsSkin' (if any)
    	partial void Merge(BootsSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class BootsSkinConverter
		{
		    partial void Merge(BootsSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region CoatSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="CoatSkin"/>.</summary>
    public sealed partial class CoatSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new CoatSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'CoatSkin' (if any)
    	partial void Merge(CoatSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class CoatSkinConverter
		{
		    partial void Merge(CoatSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region GlovesSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="GlovesSkin"/>.</summary>
    public sealed partial class GlovesSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new GlovesSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'GlovesSkin' (if any)
    	partial void Merge(GlovesSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class GlovesSkinConverter
		{
		    partial void Merge(GlovesSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region HelmAquaticSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="HelmAquaticSkin"/>.</summary>
    public sealed partial class HelmAquaticSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new HelmAquaticSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'HelmAquaticSkin' (if any)
    	partial void Merge(HelmAquaticSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class HelmAquaticSkinConverter
		{
		    partial void Merge(HelmAquaticSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region HelmSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="HelmSkin"/>.</summary>
    public sealed partial class HelmSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new HelmSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'HelmSkin' (if any)
    	partial void Merge(HelmSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class HelmSkinConverter
		{
		    partial void Merge(HelmSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region LeggingsSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="LeggingsSkin"/>.</summary>
    public sealed partial class LeggingsSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new LeggingsSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'LeggingsSkin' (if any)
    	partial void Merge(LeggingsSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class LeggingsSkinConverter
		{
		    partial void Merge(LeggingsSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region ShouldersSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="ShouldersSkin"/>.</summary>
    public sealed partial class ShouldersSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new ShouldersSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'ShouldersSkin' (if any)
    	partial void Merge(ShouldersSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class ShouldersSkinConverter
		{
		    partial void Merge(ShouldersSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownArmorSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="UnknownArmorSkin"/>.</summary>
    public sealed partial class UnknownArmorSkinConverter : IConverter<SkinDataModel, ArmorSkin>
    {
	    /// <inheritdoc />
        public ArmorSkin Convert(SkinDataModel value, object state)
        {
    		var entity = new UnknownArmorSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownArmorSkin' (if any)
    	partial void Merge(UnknownArmorSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownArmorSkinConverter
		{
		    partial void Merge(UnknownArmorSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
