//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataModel.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
    using GW2NET.Items.ApiModels;
    using GW2NET.Items.Containers;

    /// <summary>Convertes a <see cref="ItemDataModel"/> into a <see cref="Container"/> object.</summary>
    public sealed partial class ContainerConverter : IConverter<ItemDataModel, Container>
	{
	    private readonly ITypeConverterFactory<ItemDataModel, Container> converterFactory;

		/// <summary>Initalizes a new instance of the <see cref="ContainerConverter"/> class.</summary>
        /// <param name="converterFactory">The <see cref="ITypeConverterFactory{TSource,TTarget}"/>.</param>
		public ContainerConverter(ITypeConverterFactory<ItemDataModel, Container> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException(nameof(converterFactory));
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public Container Convert(ItemDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException(nameof(value));
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'Container' (if any)
    	partial void Merge(Container entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class ContainerConverter
		{
		    partial void Merge(Container entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region DefaultContainer
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="DefaultContainer"/>.</summary>
    public sealed partial class DefaultContainerConverter : IConverter<ItemDataModel, Container>
    {
	    /// <inheritdoc />
        public Container Convert(ItemDataModel value, object state)
        {
    		var entity = new DefaultContainer();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'DefaultContainer' (if any)
    	partial void Merge(DefaultContainer entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class DefaultContainerConverter
		{
		    partial void Merge(DefaultContainer entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region GiftBox
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="GiftBox"/>.</summary>
    public sealed partial class GiftBoxConverter : IConverter<ItemDataModel, Container>
    {
	    /// <inheritdoc />
        public Container Convert(ItemDataModel value, object state)
        {
    		var entity = new GiftBox();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'GiftBox' (if any)
    	partial void Merge(GiftBox entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class GiftBoxConverter
		{
		    partial void Merge(GiftBox entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region OpenUiContainer
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="OpenUiContainer"/>.</summary>
    public sealed partial class OpenUiContainerConverter : IConverter<ItemDataModel, Container>
    {
	    /// <inheritdoc />
        public Container Convert(ItemDataModel value, object state)
        {
    		var entity = new OpenUiContainer();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'OpenUiContainer' (if any)
    	partial void Merge(OpenUiContainer entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class OpenUiContainerConverter
		{
		    partial void Merge(OpenUiContainer entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownContainer
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="UnknownContainer"/>.</summary>
    public sealed partial class UnknownContainerConverter : IConverter<ItemDataModel, Container>
    {
	    /// <inheritdoc />
        public Container Convert(ItemDataModel value, object state)
        {
    		var entity = new UnknownContainer();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownContainer' (if any)
    	partial void Merge(UnknownContainer entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownContainerConverter
		{
		    partial void Merge(UnknownContainer entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
