//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataModel.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
    using GW2NET.Items.ApiModels;
    using GW2NET.Items.GatheringTools;

    /// <summary>Convertes a <see cref="ItemDataModel"/> into a <see cref="GatheringTool"/> object.</summary>
    public sealed partial class GatheringToolConverter : IConverter<ItemDataModel, GatheringTool>
	{
	    private readonly ITypeConverterFactory<ItemDataModel, GatheringTool> converterFactory;

		/// <summary>Initalizes a new instance of the <see cref="GatheringToolConverter"/> class.</summary>
        /// <param name="converterFactory">The <see cref="ITypeConverterFactory{TSource,TTarget}"/>.</param>
		public GatheringToolConverter(ITypeConverterFactory<ItemDataModel, GatheringTool> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException(nameof(converterFactory));
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public GatheringTool Convert(ItemDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException(nameof(value));
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'GatheringTool' (if any)
    	partial void Merge(GatheringTool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class GatheringToolConverter
		{
		    partial void Merge(GatheringTool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region ForagingTool
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="ForagingTool"/>.</summary>
    public sealed partial class ForagingToolConverter : IConverter<ItemDataModel, GatheringTool>
    {
	    /// <inheritdoc />
        public GatheringTool Convert(ItemDataModel value, object state)
        {
    		var entity = new ForagingTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'ForagingTool' (if any)
    	partial void Merge(ForagingTool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class ForagingToolConverter
		{
		    partial void Merge(ForagingTool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region LoggingTool
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="LoggingTool"/>.</summary>
    public sealed partial class LoggingToolConverter : IConverter<ItemDataModel, GatheringTool>
    {
	    /// <inheritdoc />
        public GatheringTool Convert(ItemDataModel value, object state)
        {
    		var entity = new LoggingTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'LoggingTool' (if any)
    	partial void Merge(LoggingTool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class LoggingToolConverter
		{
		    partial void Merge(LoggingTool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region MiningTool
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="MiningTool"/>.</summary>
    public sealed partial class MiningToolConverter : IConverter<ItemDataModel, GatheringTool>
    {
	    /// <inheritdoc />
        public GatheringTool Convert(ItemDataModel value, object state)
        {
    		var entity = new MiningTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'MiningTool' (if any)
    	partial void Merge(MiningTool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class MiningToolConverter
		{
		    partial void Merge(MiningTool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownGatheringTool
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="UnknownGatheringTool"/>.</summary>
    public sealed partial class UnknownGatheringToolConverter : IConverter<ItemDataModel, GatheringTool>
    {
	    /// <inheritdoc />
        public GatheringTool Convert(ItemDataModel value, object state)
        {
    		var entity = new UnknownGatheringTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownGatheringTool' (if any)
    	partial void Merge(UnknownGatheringTool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownGatheringToolConverter
		{
		    partial void Merge(UnknownGatheringTool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
