//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataContract.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
	using GW2NET.Items.ApiModels;
	using GW2NET.Items;

    public sealed partial class ItemConverter : IConverter<ItemDataModel, Item>
	{
	    private readonly ITypeConverterFactory<ItemDataModel, Item> converterFactory;

		private ItemConverter(ITypeConverterFactory<ItemDataModel, Item> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException("converterFactory");
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException("value");
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'Item' (if any)
    	partial void Merge(Item entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class ItemConverter
		{
		    partial void Merge(Item entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region Backpack
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="Backpack"/>.</summary>
    public sealed partial class BackpackConverter : IConverter<ItemDataModel, Item>
    {
	    /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
        {
    		var entity = new Backpack();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'Backpack' (if any)
    	partial void Merge(Backpack entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class BackpackConverter
		{
		    partial void Merge(Backpack entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region Bag
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="Bag"/>.</summary>
    public sealed partial class BagConverter : IConverter<ItemDataModel, Item>
    {
	    /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
        {
    		var entity = new Bag();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'Bag' (if any)
    	partial void Merge(Bag entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class BagConverter
		{
		    partial void Merge(Bag entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region CraftingMaterial
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="CraftingMaterial"/>.</summary>
    public sealed partial class CraftingMaterialConverter : IConverter<ItemDataModel, Item>
    {
	    /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
        {
    		var entity = new CraftingMaterial();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'CraftingMaterial' (if any)
    	partial void Merge(CraftingMaterial entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class CraftingMaterialConverter
		{
		    partial void Merge(CraftingMaterial entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region Miniature
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="Miniature"/>.</summary>
    public sealed partial class MiniatureConverter : IConverter<ItemDataModel, Item>
    {
	    /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
        {
    		var entity = new Miniature();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'Miniature' (if any)
    	partial void Merge(Miniature entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class MiniatureConverter
		{
		    partial void Merge(Miniature entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region TraitGuide
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="TraitGuide"/>.</summary>
    public sealed partial class TraitGuideConverter : IConverter<ItemDataModel, Item>
    {
	    /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
        {
    		var entity = new TraitGuide();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'TraitGuide' (if any)
    	partial void Merge(TraitGuide entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class TraitGuideConverter
		{
		    partial void Merge(TraitGuide entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region Trophy
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="Trophy"/>.</summary>
    public sealed partial class TrophyConverter : IConverter<ItemDataModel, Item>
    {
	    /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
        {
    		var entity = new Trophy();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'Trophy' (if any)
    	partial void Merge(Trophy entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class TrophyConverter
		{
		    partial void Merge(Trophy entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownItem
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="UnknownItem"/>.</summary>
    public sealed partial class UnknownItemConverter : IConverter<ItemDataModel, Item>
    {
	    /// <inheritdoc />
        public Item Convert(ItemDataModel value, object state)
        {
    		var entity = new UnknownItem();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownItem' (if any)
    	partial void Merge(UnknownItem entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownItemConverter
		{
		    partial void Merge(UnknownItem entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
