//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataModel.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
	using GW2NET.Items.ApiModels;
	using GW2NET.Skins;

    /// <summary>Convertes a <see cref="SkinDataModel"/> into a <see cref="Skin"/> object.</summary>
    public sealed partial class SkinConverter : IConverter<SkinDataModel, Skin>
	{
	    private readonly ITypeConverterFactory<SkinDataModel, Skin> converterFactory;

		/// <summary>Initalizes a new instance of the <see cref="SkinConverter"/> class.</summary>
        /// <param name="converterFactory">The <see cref="ITypeConverterFactory{TSource,TTarget}"/>.</param>
		private SkinConverter(ITypeConverterFactory<SkinDataModel, Skin> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException(nameof(converterFactory));
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public Skin Convert(SkinDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException(nameof(value));
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'Skin' (if any)
    	partial void Merge(Skin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class SkinConverter
		{
		    partial void Merge(Skin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region BackpackSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="BackpackSkin"/>.</summary>
    public sealed partial class BackpackSkinConverter : IConverter<SkinDataModel, Skin>
    {
	    /// <inheritdoc />
        public Skin Convert(SkinDataModel value, object state)
        {
    		var entity = new BackpackSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'BackpackSkin' (if any)
    	partial void Merge(BackpackSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class BackpackSkinConverter
		{
		    partial void Merge(BackpackSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownSkin
    /// <summary>Converts objects of type <see cref="SkinDataModel"/> to objects of type <see cref="UnknownSkin"/>.</summary>
    public sealed partial class UnknownSkinConverter : IConverter<SkinDataModel, Skin>
    {
	    /// <inheritdoc />
        public Skin Convert(SkinDataModel value, object state)
        {
    		var entity = new UnknownSkin();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownSkin' (if any)
    	partial void Merge(UnknownSkin entity, SkinDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownSkinConverter
		{
		    partial void Merge(UnknownSkin entity, SkinDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
