//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataContract.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
	using GW2NET.Items.ApiModels;
	using GW2NET.Items;

    public sealed partial class ToolConverter : IConverter<ItemDataModel, Tool>
	{
	    private readonly ITypeConverterFactory<ItemDataModel, Tool> converterFactory;

		public ToolConverter(ITypeConverterFactory<ItemDataModel, Tool> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException("converterFactory");
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public Tool Convert(ItemDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException("value");
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'Tool' (if any)
    	partial void Merge(Tool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class ToolConverter
		{
		    partial void Merge(Tool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region SalvageTool
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="SalvageTool"/>.</summary>
    public sealed partial class SalvageToolConverter : IConverter<ItemDataModel, Tool>
    {
	    /// <inheritdoc />
        public Tool Convert(ItemDataModel value, object state)
        {
    		var entity = new SalvageTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'SalvageTool' (if any)
    	partial void Merge(SalvageTool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class SalvageToolConverter
		{
		    partial void Merge(SalvageTool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownTool
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="UnknownTool"/>.</summary>
    public sealed partial class UnknownToolConverter : IConverter<ItemDataModel, Tool>
    {
	    /// <inheritdoc />
        public Tool Convert(ItemDataModel value, object state)
        {
    		var entity = new UnknownTool();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownTool' (if any)
    	partial void Merge(UnknownTool entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownToolConverter
		{
		    partial void Merge(UnknownTool entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
