//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataModel.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
    using GW2NET.Items.ApiModels;
    using GW2NET.Items.Consumables;

    /// <summary>Convertes a <see cref="ItemDataModel"/> into a <see cref="Unlocker"/> object.</summary>
    public sealed partial class UnlockerConverter : IConverter<ItemDataModel, Unlocker>
	{
	    private readonly ITypeConverterFactory<ItemDataModel, Unlocker> converterFactory;

		/// <summary>Initalizes a new instance of the <see cref="UnlockerConverter"/> class.</summary>
        /// <param name="converterFactory">The <see cref="ITypeConverterFactory{TSource,TTarget}"/>.</param>
		public UnlockerConverter(ITypeConverterFactory<ItemDataModel, Unlocker> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException(nameof(converterFactory));
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException(nameof(value));
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'Unlocker' (if any)
    	partial void Merge(Unlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UnlockerConverter
		{
		    partial void Merge(Unlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region ChampionUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="ChampionUnlocker"/>.</summary>
    public sealed partial class ChampionUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new ChampionUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'ChampionUnlocker' (if any)
    	partial void Merge(ChampionUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class ChampionUnlockerConverter
		{
		    partial void Merge(ChampionUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region GliderSkinUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="GliderSkinUnlocker"/>.</summary>
    public sealed partial class GliderSkinUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new GliderSkinUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'GliderSkinUnlocker' (if any)
    	partial void Merge(GliderSkinUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class GliderSkinUnlockerConverter
		{
		    partial void Merge(GliderSkinUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region OutfitUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="OutfitUnlocker"/>.</summary>
    public sealed partial class OutfitUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new OutfitUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'OutfitUnlocker' (if any)
    	partial void Merge(OutfitUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class OutfitUnlockerConverter
		{
		    partial void Merge(OutfitUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region BagSlotUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="BagSlotUnlocker"/>.</summary>
    public sealed partial class BagSlotUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new BagSlotUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'BagSlotUnlocker' (if any)
    	partial void Merge(BagSlotUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class BagSlotUnlockerConverter
		{
		    partial void Merge(BagSlotUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region BankTabUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="BankTabUnlocker"/>.</summary>
    public sealed partial class BankTabUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new BankTabUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'BankTabUnlocker' (if any)
    	partial void Merge(BankTabUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class BankTabUnlockerConverter
		{
		    partial void Merge(BankTabUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region CollectibleCapacityUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="CollectibleCapacityUnlocker"/>.</summary>
    public sealed partial class CollectibleCapacityUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new CollectibleCapacityUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'CollectibleCapacityUnlocker' (if any)
    	partial void Merge(CollectibleCapacityUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class CollectibleCapacityUnlockerConverter
		{
		    partial void Merge(CollectibleCapacityUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region ContentUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="ContentUnlocker"/>.</summary>
    public sealed partial class ContentUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new ContentUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'ContentUnlocker' (if any)
    	partial void Merge(ContentUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class ContentUnlockerConverter
		{
		    partial void Merge(ContentUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region CraftingRecipeUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="CraftingRecipeUnlocker"/>.</summary>
    public sealed partial class CraftingRecipeUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new CraftingRecipeUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'CraftingRecipeUnlocker' (if any)
    	partial void Merge(CraftingRecipeUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class CraftingRecipeUnlockerConverter
		{
		    partial void Merge(CraftingRecipeUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region DyeUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="DyeUnlocker"/>.</summary>
    public sealed partial class DyeUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new DyeUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'DyeUnlocker' (if any)
    	partial void Merge(DyeUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class DyeUnlockerConverter
		{
		    partial void Merge(DyeUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownUnlocker
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="UnknownUnlocker"/>.</summary>
    public sealed partial class UnknownUnlockerConverter : IConverter<ItemDataModel, Unlocker>
    {
	    /// <inheritdoc />
        public Unlocker Convert(ItemDataModel value, object state)
        {
    		var entity = new UnknownUnlocker();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownUnlocker' (if any)
    	partial void Merge(UnknownUnlocker entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownUnlockerConverter
		{
		    partial void Merge(UnknownUnlocker entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
