//---------------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// <copyright file="SkinDataModel.cs" company="GW2.NET Coding Team">
//     This product is licensed under the GNU General Public License version 2 (GPLv2).
//     See the License in the project root folder or the following page: http://www.gnu.org/licenses/gpl-2.0.html
// </copyright>
//---------------------------------------------------------------------------------------------------------------------------

namespace GW2NET.Items.Converter
{
    using System;

    using GW2NET.Common;
    using GW2NET.Items.ApiModels;
    using GW2NET.Items.UpgradeComponents;

    /// <summary>Convertes a <see cref="ItemDataModel"/> into a <see cref="UpgradeComponent"/> object.</summary>
    public sealed partial class UpgradeComponentConverter : IConverter<ItemDataModel, UpgradeComponent>
	{
	    private readonly ITypeConverterFactory<ItemDataModel, UpgradeComponent> converterFactory;

		/// <summary>Initalizes a new instance of the <see cref="UpgradeComponentConverter"/> class.</summary>
        /// <param name="converterFactory">The <see cref="ITypeConverterFactory{TSource,TTarget}"/>.</param>
		private UpgradeComponentConverter(ITypeConverterFactory<ItemDataModel, UpgradeComponent> converterFactory)
		{
		    if (converterFactory == null)
    		{
    		    throw new ArgumentNullException(nameof(converterFactory));
    		}

		    this.converterFactory = converterFactory;
		}

		 /// <inheritdoc />
        public UpgradeComponent Convert(ItemDataModel value, object state)
		{
		    if (value == null)
    		{
    		    throw new ArgumentNullException(nameof(value));
    		}

			string discriminator = value.Details.Type;
			var converter = this.converterFactory.Create(discriminator);
			var entity = converter.Convert(value, value);
			this.Merge(entity, value, state);
			return entity;
		}

		// Implement this method in a buddy class to set properties that are specific to 'UpgradeComponent' (if any)
    	partial void Merge(UpgradeComponent entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UpgradeComponentConverter
		{
		    partial void Merge(UpgradeComponent entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
	}

#region DefaultUpgradeComponent
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="DefaultUpgradeComponent"/>.</summary>
    public sealed partial class DefaultUpgradeComponentConverter : IConverter<ItemDataModel, UpgradeComponent>
    {
	    /// <inheritdoc />
        public UpgradeComponent Convert(ItemDataModel value, object state)
        {
    		var entity = new DefaultUpgradeComponent();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'DefaultUpgradeComponent' (if any)
    	partial void Merge(DefaultUpgradeComponent entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class DefaultUpgradeComponentConverter
		{
		    partial void Merge(DefaultUpgradeComponent entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region Gem
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="Gem"/>.</summary>
    public sealed partial class GemConverter : IConverter<ItemDataModel, UpgradeComponent>
    {
	    /// <inheritdoc />
        public UpgradeComponent Convert(ItemDataModel value, object state)
        {
    		var entity = new Gem();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'Gem' (if any)
    	partial void Merge(Gem entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class GemConverter
		{
		    partial void Merge(Gem entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region Rune
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="Rune"/>.</summary>
    public sealed partial class RuneConverter : IConverter<ItemDataModel, UpgradeComponent>
    {
	    /// <inheritdoc />
        public UpgradeComponent Convert(ItemDataModel value, object state)
        {
    		var entity = new Rune();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'Rune' (if any)
    	partial void Merge(Rune entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class RuneConverter
		{
		    partial void Merge(Rune entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region Sigil
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="Sigil"/>.</summary>
    public sealed partial class SigilConverter : IConverter<ItemDataModel, UpgradeComponent>
    {
	    /// <inheritdoc />
        public UpgradeComponent Convert(ItemDataModel value, object state)
        {
    		var entity = new Sigil();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'Sigil' (if any)
    	partial void Merge(Sigil entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class SigilConverter
		{
		    partial void Merge(Sigil entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

#region UnknownUpgradeComponent
    /// <summary>Converts objects of type <see cref="ItemDataModel"/> to objects of type <see cref="UnknownUpgradeComponent"/>.</summary>
    public sealed partial class UnknownUpgradeComponentConverter : IConverter<ItemDataModel, UpgradeComponent>
    {
	    /// <inheritdoc />
        public UpgradeComponent Convert(ItemDataModel value, object state)
        {
    		var entity = new UnknownUpgradeComponent();
            this.Merge(entity, value, state);
    		return entity;
        }

    	// Implement this method in a buddy class to set properties that are specific to 'UnknownUpgradeComponent' (if any)
    	partial void Merge(UnknownUpgradeComponent entity, ItemDataModel dto, object state);

		/*
		// Use this template
		public partial class UnknownUpgradeComponentConverter
		{
		    partial void Merge(UnknownUpgradeComponent entity, ItemDataModel dto, object state)
			{
			    throw new NotImplementedException();
			}
		}
		*/
    }
#endregion

}
